//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabelWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class GetPreview
    {
        public string Artikelname { get; set; }
        public string Artikelnummer { get; set; }
        public string Artikeltyp { get; set; }
        public int Kundenlogonummer { get; set; }
        public Nullable<int> Artikeldaten { get; set; }
        public Nullable<int> EtikettenVariante { get; set; }
        public string Kundenartikelnummer { get; set; }
        public string Barcode { get; set; }
        public string Etikett { get; set; }
        public string Logo { get; set; }
    }
}
